### ISSUE TITLE
Calculus Windows

### ISSUE THREAD

**Issue by Sempyos** [Mnemotechnician/calculus#2]
Can you try to make it so that windows can collide or make it a setting?

**Comment by Mnemotechnician** [comment]
I don't even understand what you mean nor how NC is related to that

**Comment by Mnemotechnician** [comment]
?
why did you close without any explainations

**Comment by Sempyos** [comment]
@Mnemotechnician Sorry about that I just needed some space to think.
Want I meant is to have a option in the settings menu to make it so that your Windows will collide with each other like they do if the edges of the game screen.

And if you could add a unit spawner that would be handy.

Sorry for the wait and inconvenience  and I just was busy and having a bit of trouble with stuff, but if you'd try to do this that would be great.
Also I use new controls which is very nice.

**Comment by Mnemotechnician** [comment]
I don't think i can make them collide

Sandbox utilities are already in development but I'm procrastinating a lot

**Comment by Sempyos** [comment]
@Mnemotechnician Ok then I'll close this issue
