### ISSUE TITLE
Unit spawner only spawns one team

### ISSUE THREAD

**Issue by Sempyos** [Mnemotechnician/calculus#3]
You should check the player's current team and have units spawn as that

**Comment by Mnemotechnician** [comment]
bruh

The box with `1` next to it allows you to choose the unit team
The box with `2` allows you to set it's type

![IMG_20220125_185233](https://user-images.githubusercontent.com/69920617/151011306-3945b017-6428-40a4-9305-f16df93fac85.jpg)

**Comment by Sempyos** [comment]
I tried that just did sharded

**Comment by Mnemotechnician** [comment]
that's because other teams have no cores

although that could be fixed if I wasn't procrastinating

**Comment by Mnemotechnician** [comment]
yeah it will be fixed in this release

**Comment by Sempyos** [comment]
Thanks
